export const FORM_PROJECT = "FORM_PROJECT";
export const OBTAIN_PROJECTS = "OBTAIN_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const VALIDATE_FROM = "VALIDATE_FROM";
export const ACTUAL_PROJECT = "ACTUAL_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const VALIDATE_TASK = "VALIDATE_TASK";
